// Generated by CoffeeScript 1.6.2
(function() {
  ko.bindingHandlers["ext"] = {
    init: function(element, valueAccessor) {
      var e, name, options, _options, _results;
      options = ko.toJS(valueAccessor()) || {};
      _results = [];
      for (name in options) {
        _options = options[name];
        try {
          _results.push($(element)[name](_options));
        } catch (_error) {
          e = _error;
          _results.push(console.log(e));
        }
      }
      return _results;
    }
  };

}).call(this);
